### ISSUE TITLE
How do you get emotes to work?

### ISSUE THREAD

**Issue by christianboyle** [KimbaWLion/DiscordBaseballBot#1]
Wondering how to get emotes to work. Great bot btw!

**Comment by KimbaWLion** [comment]
https://old.reddit.com/r/discordapp/comments/58t9x8/how_do_i_make_a_bot_type_an_emojiserver_emoji/d932ksh/?context=1

> The emoji Name/ID should be obtained with `\:emoji:` then typed as `<emoji_name:id>` in the bot code

Glad you like the bot!
