### ISSUE TITLE
Error after running

### ISSUE THREAD

**Issue by hoddino** [KimbaWLion/DiscordBaseballBot#4]
I'm trying to get the bot working, and I have everything installed but I think my versions are not right. I'm new to Python and can't seem to get an older version of discord or aiohttp. This is what I get when I launch

C:\scripts\DiscordBaseballBot-master\BaseballConsumer>python MainEntryBot.py
Task exception was never retrieved
future: <Task finished coro=<my_background_task() done, defined at MainEntryBot.py:43> exception=JSONDecodeError('Invalid \\escape: line 2 column 27 (char 28)',)>
Traceback (most recent call last):
  File "MainEntryBot.py", line 51, in my_background_task
    await baseballUpdaterBotV2.run(client, channel)
  File "C:\scripts\DiscordBaseballBot-master\BaseballConsumer\BaseballConsumerV2.py", line 24, in run
    error_msg = self.read_settings()
  File "C:\scripts\DiscordBaseballBot-master\BaseballConsumer\BaseballConsumerV2.py", line 174, in read_settings
    settings = json.load(data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 27 (char 28)
Logged in as....

**Comment by KimbaWLion** [comment]
This line
` json.decoder.JSONDecodeError: Invalid \escape: line 2 column 27 (char 28)`
says that it couldn't decode your json, check you settings file into https://jsonlint.com/ to see if your json is valid

**Comment by hoddino** [comment]
Where would I find that file?

**edit** oh nevermind that's the settings.json file. Checking it now!

**Comment by KimbaWLion** [comment]
also check the discordSettings.doNotUplaod.json file

**Comment by hoddino** [comment]
{
    "GAME_THREAD_LOG": "C:\scripts\DiscordBaseballBot-master\BaseballConsumer\logs\game_thread.now"
    "TEAM_ID": 141
}

**Comment by KimbaWLion** [comment]
You forgot a comma, add it at the end of the string
```
{
"GAME_THREAD_LOG": "C:\scripts\DiscordBaseballBot-master\BaseballConsumer\logs\game_thread.now",
"TEAM_ID": 141
}
````

**Comment by KimbaWLion** [comment]
Also make sure your discordSettings.doNotUpload.json file has commas too (and do not post your tokens here ;) )

**Comment by hoddino** [comment]
yeah added the comma and still get the same error. Checking it, it shows this. The discordSettings file is working perfect as the bot is joining the server without issue :)
Error: Parse error on line 2:
...	"GAME_THREAD_LOG": "C:\scripts\DiscordB
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by KimbaWLion** [comment]
I legit have no clue what's happening there.  Could you post your full error in a code block (wrap it in 3 backslashes) and remove all sensitive info such as your name and whatnot.

**Comment by hoddino** [comment]
Not sure which error you would like me to post.

**Comment by KimbaWLion** [comment]
whichever one shows up when you try to run MainEntryBot.py

**Comment by hoddino** [comment]
\\\C:\scripts\DiscordBaseballBot-master\BaseballConsumer>python MainEntryBot.py
Task exception was never retrieved
future: <Task finished coro=<my_background_task() done, defined at MainEntryBot.py:43> exception=JSONDecodeError('Invalid \\escape: line 2 column 24 (char 25)',)>
Traceback (most recent call last):
  File "MainEntryBot.py", line 51, in my_background_task
    await baseballUpdaterBotV2.run(client, channel)
  File "C:\scripts\DiscordBaseballBot-master\BaseballConsumer\BaseballConsumerV2.py", line 24, in run
    error_msg = self.read_settings()
  File "C:\scripts\DiscordBaseballBot-master\BaseballConsumer\BaseballConsumerV2.py", line 174, in read_settings
    settings = json.load(data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 24 (char 25)
Logged in as
MLB_Action_Bot
*************************
------

C:\scripts\DiscordBaseballBot-master\BaseballConsumer>

**Comment by KimbaWLion** [comment]
Oh wow, let's see if this works.

According to this (https://stackoverflow.com/questions/44687525/json-reading-error-json-decoder-jsondecodeerror-invalid-escape), your backslashes in your GAME_THREAD_LOG path are making escape characters, including "`\l`".  Try changing them all to forward slashes:

```
{
"GAME_THREAD_LOG": "C:/scripts/DiscordBaseballBot-master/BaseballConsumer/logs/game_thread.now",
"TEAM_ID": 141
}
```

**Comment by hoddino** [comment]
That did it! Everything is working perfectly and the bot just spammed the crap out of my channel...LOL
Just to be clear to get the path to the file, I shift-right clicked in Windows on the file and did "Copy as path".

Thanks for the quick replies!

**Comment by KimbaWLion** [comment]
Glad we were able to resolve the issue, thank you for using the bot!
