### ISSUE TITLE
Can not find discordSettings.doNotUpload.json

### ISSUE THREAD

**Issue by RABlue27** [KimbaWLion/DiscordBaseballBot#5]
Hey y'all, can't seem to get this file found, and as such it throws an error. JSON is valid and file paths are correct. Source code doesn't work nor does any attempt to correct the path. 

Exact error traceback:
```
Traceback (most recent call last):
  File "MainEntryBot.py", line 62, in <module>
    error_msg = read_settings()
  File "MainEntryBot.py", line 20, in read_settings
    with open(SETTINGS_FILE) as data:
FileNotFoundError: [Errno 2] No such file or directory: './discordSettings.doNotUpload.json'
```

**Comment by KimbaWLion** [comment]
Could you post what your file structure is?  It should match the File Structure as shown in the README in the "FileMap when running bot" section

```
DiscordBaseballBot (directory)
∟ README.md
∟ settings.json
∟ discordSettings.doNotUpload.json
∟ BaseballConsumer (directory)
  ∟ __init__.py
  ∟ BaseballConsumerV2.py
  ∟ BaseballConsumerConstants.py
  ∟ TeamAndStandingsUtilities.py
  ∟ MainEntryBot.py
  ∟ logs (directory)
    ∟ game_thread.now

```

**Comment by KimbaWLion** [comment]
Also check what the working directory is.  The working directory should be the top level directory "DiscordBaseballBot".

This seems a bit unintuitive if the working directory is the issue, I'll change it if that's the case.
